"""
    OneLogin API

    OneLogin API generated with openapi-generator

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.mapping_id_list import MappingIdList


class TestMappingIdList(unittest.TestCase):
    """MappingIdList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMappingIdList(self):
        """Test MappingIdList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MappingIdList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
