# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import onelogin
from onelogin.models.update_password_secure_request import UpdatePasswordSecureRequest  # noqa: E501
from onelogin.rest import ApiException

class TestUpdatePasswordSecureRequest(unittest.TestCase):
    """UpdatePasswordSecureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdatePasswordSecureRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePasswordSecureRequest`
        """
        model = onelogin.models.update_password_secure_request.UpdatePasswordSecureRequest()  # noqa: E501
        if include_optional :
            return UpdatePasswordSecureRequest(
                password = 'xxxxx637aead4030a653f29dae62f1542d67484342c00627a65066e05c5f0', 
                password_confirmation = 'xxxxx637aead4030a653f29dae62f1542d67484342c00627a65066e05c5f0', 
                password_algorithm = 'salt+sha256', 
                password_salt = '11xxxx1'
            )
        else :
            return UpdatePasswordSecureRequest(
                password = 'xxxxx637aead4030a653f29dae62f1542d67484342c00627a65066e05c5f0',
                password_confirmation = 'xxxxx637aead4030a653f29dae62f1542d67484342c00627a65066e05c5f0',
                password_algorithm = 'salt+sha256',
        )
        """

    def testUpdatePasswordSecureRequest(self):
        """Test UpdatePasswordSecureRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
