"""
    OneLogin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.0-beta.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.event import Event
from onelogin.model.v1_status import V1Status
globals()['Event'] = Event
globals()['V1Status'] = V1Status
from onelogin.model.get_event_by_id200_response import GetEventById200Response


class TestGetEventById200Response(unittest.TestCase):
    """GetEventById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEventById200Response(self):
        """Test GetEventById200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEventById200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
