"""
    OneLogin API

    OneLogin API generated with openapi-generator

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.device import Device


class TestDevice(unittest.TestCase):
    """Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevice(self):
        """Test Device"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Device()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
