"""
    OneLogin API

    OneLogin API generated with openapi-generator

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.factor_inner_factor_data import FactorInnerFactorData
globals()['FactorInnerFactorData'] = FactorInnerFactorData
from onelogin.model.factor_inner import FactorInner


class TestFactorInner(unittest.TestCase):
    """FactorInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFactorInner(self):
        """Test FactorInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FactorInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
