"""
    OneLogin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.risk_device import RiskDevice


class TestRiskDevice(unittest.TestCase):
    """RiskDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskDevice(self):
        """Test RiskDevice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskDevice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
