# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import onelogin
from onelogin.models.get_user_verification200_response import GetUserVerification200Response  # noqa: E501
from onelogin.rest import ApiException

class TestGetUserVerification200Response(unittest.TestCase):
    """GetUserVerification200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetUserVerification200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserVerification200Response`
        """
        model = onelogin.models.get_user_verification200_response.GetUserVerification200Response()  # noqa: E501
        if include_optional :
            return GetUserVerification200Response(
                id = '5a0ba80a-39a1-4627-9a8b-1273278b34ee', 
                status = 'pending', 
                device_id = '331991'
            )
        else :
            return GetUserVerification200Response(
        )
        """

    def testGetUserVerification200Response(self):
        """Test GetUserVerification200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
