# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import onelogin
from onelogin.models.enroll_mfa_factor_request import EnrollMfaFactorRequest  # noqa: E501
from onelogin.rest import ApiException

class TestEnrollMfaFactorRequest(unittest.TestCase):
    """EnrollMfaFactorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EnrollMfaFactorRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnrollMfaFactorRequest`
        """
        model = onelogin.models.enroll_mfa_factor_request.EnrollMfaFactorRequest()  # noqa: E501
        if include_optional :
            return EnrollMfaFactorRequest(
                factor_id = 16282, 
                display_name = 'Rich's Phone', 
                number = '+1xxxxxxxxxx', 
                verified = True
            )
        else :
            return EnrollMfaFactorRequest(
                factor_id = 16282,
                display_name = 'Rich's Phone',
                number = '+1xxxxxxxxxx',
        )
        """

    def testEnrollMfaFactorRequest(self):
        """Test EnrollMfaFactorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
