# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import onelogin
from onelogin.models.action_obj import ActionObj  # noqa: E501
from onelogin.rest import ApiException

class TestActionObj(unittest.TestCase):
    """ActionObj unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ActionObj
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionObj`
        """
        model = onelogin.models.action_obj.ActionObj()  # noqa: E501
        if include_optional :
            return ActionObj(
                action = '', 
                value = [
                    '2'
                    ]
            )
        else :
            return ActionObj(
        )
        """

    def testActionObj(self):
        """Test ActionObj"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
