"""
    OneLogin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.auth_server_configuration import AuthServerConfiguration
globals()['AuthServerConfiguration'] = AuthServerConfiguration
from openapi_client.model.create_authorization_server_request import CreateAuthorizationServerRequest


class TestCreateAuthorizationServerRequest(unittest.TestCase):
    """CreateAuthorizationServerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAuthorizationServerRequest(self):
        """Test CreateAuthorizationServerRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateAuthorizationServerRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
