"""
    OneLogin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.factor_inner import FactorInner
globals()['FactorInner'] = FactorInner
from openapi_client.model.factor import Factor


class TestFactor(unittest.TestCase):
    """Factor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFactor(self):
        """Test Factor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Factor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
