"""
    OneLogin API

    OneLogin API generated with openapi-generator

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.activate_factor_request import ActivateFactorRequest


class TestActivateFactorRequest(unittest.TestCase):
    """ActivateFactorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivateFactorRequest(self):
        """Test ActivateFactorRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivateFactorRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
