# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import onelogin
from onelogin.models.saml_factor import SamlFactor  # noqa: E501
from onelogin.rest import ApiException

class TestSamlFactor(unittest.TestCase):
    """SamlFactor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SamlFactor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SamlFactor`
        """
        model = onelogin.models.saml_factor.SamlFactor()  # noqa: E501
        if include_optional :
            return SamlFactor(
                app_id = '1657651', 
                device_id = '1657651', 
                state_token = '11x0x1x16x1x3259xxxx0x59xx6xxxx670x61x45xxxxx', 
                otp_token = '999999', 
                do_not_notify = False
            )
        else :
            return SamlFactor(
                app_id = '1657651',
                device_id = '1657651',
                state_token = '11x0x1x16x1x3259xxxx0x59xx6xxxx670x61x45xxxxx',
        )
        """

    def testSamlFactor(self):
        """Test SamlFactor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
