"""
    OneLogin API

    OneLogin API generated with openapi-generator

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.hook_options import HookOptions


class TestHookOptions(unittest.TestCase):
    """HookOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHookOptions(self):
        """Test HookOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HookOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
