# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import onelogin
from onelogin.models.create_scope200_response import CreateScope200Response  # noqa: E501
from onelogin.rest import ApiException

class TestCreateScope200Response(unittest.TestCase):
    """CreateScope200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateScope200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateScope200Response`
        """
        model = onelogin.models.create_scope200_response.CreateScope200Response()  # noqa: E501
        if include_optional :
            return CreateScope200Response(
                id = 323005
            )
        else :
            return CreateScope200Response(
        )
        """

    def testCreateScope200Response(self):
        """Test CreateScope200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
