"""
    OneLogin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.0-beta.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.group import Group
from onelogin.model.v1_status import V1Status
globals()['Group'] = Group
globals()['V1Status'] = V1Status
from onelogin.model.get_group_by_id200_response import GetGroupById200Response


class TestGetGroupById200Response(unittest.TestCase):
    """GetGroupById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetGroupById200Response(self):
        """Test GetGroupById200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetGroupById200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
