# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import onelogin
from onelogin.models.create_factor_registration_request import CreateFactorRegistrationRequest  # noqa: E501
from onelogin.rest import ApiException

class TestCreateFactorRegistrationRequest(unittest.TestCase):
    """CreateFactorRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateFactorRegistrationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFactorRegistrationRequest`
        """
        model = onelogin.models.create_factor_registration_request.CreateFactorRegistrationRequest()  # noqa: E501
        if include_optional :
            return CreateFactorRegistrationRequest(
                factor_id = 58959, 
                display_name = 'OneLogin SMS', 
                expires_in = '', 
                verified = True, 
                redirect_to = '', 
                custom_message = ''
            )
        else :
            return CreateFactorRegistrationRequest(
                factor_id = 58959,
                display_name = 'OneLogin SMS',
        )
        """

    def testCreateFactorRegistrationRequest(self):
        """Test CreateFactorRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
