"""
    OneLogin API

    OneLogin API generated with openapi-generator

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onelogin
from onelogin.model.get_score_insights200_response_scores import GetScoreInsights200ResponseScores


class TestGetScoreInsights200ResponseScores(unittest.TestCase):
    """GetScoreInsights200ResponseScores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetScoreInsights200ResponseScores(self):
        """Test GetScoreInsights200ResponseScores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetScoreInsights200ResponseScores()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
