"""
    OneLogin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_actions200_response_inner import ListActions200ResponseInner


class TestListActions200ResponseInner(unittest.TestCase):
    """ListActions200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListActions200ResponseInner(self):
        """Test ListActions200ResponseInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListActions200ResponseInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
