# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import onelogin
from onelogin.models.get_role_by_id200_response import GetRoleById200Response  # noqa: E501
from onelogin.rest import ApiException

class TestGetRoleById200Response(unittest.TestCase):
    """GetRoleById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetRoleById200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRoleById200Response`
        """
        model = onelogin.models.get_role_by_id200_response.GetRoleById200Response()  # noqa: E501
        if include_optional :
            return GetRoleById200Response(
                status = onelogin.models.error.Error(
                    error = False, 
                    code = 200, 
                    type = 'Success', 
                    message = 'Success', ), 
                data = [
                    onelogin.models.get_role_by_id_200_response_data_inner.getRoleById_200_response_data_inner(
                        id = 123456, 
                        name = 'Employee', )
                    ]
            )
        else :
            return GetRoleById200Response(
        )
        """

    def testGetRoleById200Response(self):
        """Test GetRoleById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
