# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import onelogin
from onelogin.models.get_brand_apps200_response_inner import GetBrandApps200ResponseInner  # noqa: E501
from onelogin.rest import ApiException

class TestGetBrandApps200ResponseInner(unittest.TestCase):
    """GetBrandApps200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetBrandApps200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBrandApps200ResponseInner`
        """
        model = onelogin.models.get_brand_apps200_response_inner.GetBrandApps200ResponseInner()  # noqa: E501
        if include_optional :
            return GetBrandApps200ResponseInner(
                id = 1455, 
                updated_at = '2020-09-11T19:35:08.288Z', 
                name = 'Mom Corp', 
                connector_id = 3001, 
                auth_method_description = 'SAML2.0', 
                description = 'Mom’s Friendly Robot Company', 
                auth_method = 2, 
                created_at = '2020-09-08T22:24:19.551Z', 
                visible = True
            )
        else :
            return GetBrandApps200ResponseInner(
                id = 1455,
                updated_at = '2020-09-11T19:35:08.288Z',
                name = 'Mom Corp',
                connector_id = 3001,
                auth_method_description = 'SAML2.0',
                description = 'Mom’s Friendly Robot Company',
                auth_method = 2,
                created_at = '2020-09-08T22:24:19.551Z',
                visible = True,
        )
        """

    def testGetBrandApps200ResponseInner(self):
        """Test GetBrandApps200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
