# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import onelogin
from onelogin.model.enforcement_point import EnforcementPoint
from onelogin import configuration


class TestEnforcementPoint(unittest.TestCase):
    """EnforcementPoint unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
