# coding: utf-8

"""
    OneLogin API

    OpenAPI Specification for OneLogin  # noqa: E501

    The version of the OpenAPI document: 3.1.1
    Generated by: https://openapi-generator.tech
"""

from onelogin.paths.api_1_invites_get_invite_link.post import GetInviteLink
from onelogin.paths.api_1_invites_send_invite_link.post import SendInviteLink


class InviteLinksApi(
    GetInviteLink,
    SendInviteLink,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
